project:
  type: website
  preview:
    port: 4200

website:
  title: "Germ치n Blesio"
  description: "Personal site - Germ치n Blesio"


  sidebar:
    # - title: Germ치n Blesio
      style: docked
      search: false
      # background: dark
      # header: Germ치n Blesio
      contents: 
        - text: Personal data
          file: index.qmd
        - text: Research
          file: index.qmd#research
        - text: Employment
          file: index.qmd#employment
        - text: Publications
          file: index.qmd#publications
        - text: Teaching experience
          file: index.qmd#teaching-experience

format:
  html:
    theme: 
      - cosmo
      - styles.scss
    toc: false
    lang: en
    # lang: es
    format-links: false
